


spring:
  # 数据源
  datasource:
    default:
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:mysql://10.130.161.2:3307/soil?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: CaeriSQL01!
    soil:
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:mysql://10.130.161.2:3307/soil?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: CaeriSQL01!


